<a href="https://colab.research.google.com/github/JakeOh/202205_itw_bd34/blob/main/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

# `np.ndarray` 속성(attribute)

In [2]:
arr = np.ones(shape=(2, 3))  # 모든 원소의 값이 1.0인 (2, 3) 모양의 배열
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [3]:
arr.dtype  # 배열의 원소들의 데이터 타입

dtype('float64')

In [4]:
arr.shape  # 모양(shape): 배열의 각 축(axis)을 따라서 있는 원소의 개수 -> tuple

(2, 3)

In [5]:
arr.ndim  # 차원(dimension): 배열의 축의 개수.

2

In [6]:
arr.size  # 크기: 배열의 원소 전체 개수

6

In [7]:
arr = np.arange(10)  # [0, 10) 범위의 정수들로 이루어진 1차원 배열.
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
arr.shape

(10,)

In [9]:
arr.ndim

1

In [11]:
arr = np.arange(1, 25).reshape((2, 3, 4))
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [12]:
arr.ndim

3

In [13]:
arr.shape

(2, 3, 4)

In [14]:
arr.dtype

dtype('int64')

# indexing

In [15]:
print(arr)  #> 3차원 배열

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [16]:
print(arr[0])  #> 2차원 배열

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
print(arr[0, 0])  #> 1차원 배열  # arr[0][0]

[1 2 3 4]


In [18]:
print(arr[0, 0, 0])  #> 원소(scalar)  # arr[0][0][0]

1



*   Python list의 인덱스 사용 방법: `list[i][j]...`
*   numpy ndarray의 인덱스 사용 방법:
    * `array[i][j]...`
    * `array[i, j, ...]`


# slicing

## 1차원 배열 slicing

In [19]:
np.random.seed(1)
arr = np.random.randint(100, size=10)  # [0, 100) 범위의 정수 난수 10개로 이루어진 1차원 배열.
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [20]:
print(arr[1:5])  # [1, 5) 인덱스의 원소들로 이루어진 "1차원 배열"

[12 72  9 75]


In [21]:
print(arr[:3])  # 배열에서 첫 3개의 원소들을 slicing

[37 12 72]


In [22]:
print(arr[-3:])  # 배열에서 마지막 3개의 원소들을 slicing

[64 16  1]


In [23]:
print(arr[0:1])  #> 1차원 배열을 slicing ==> "1차원 배열"!

[37]


In [24]:
print(arr[0])  # indexing: 원소 1개 선택.

37


## 2차원 배열 slicing

In [25]:
arr = np.arange(20).reshape((4, 5))
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [26]:
# 첫 2개 row 선택, 모든 column 선택
print(arr[:2, :])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [27]:
# 첫 2개의 row 선택, 첫 3개의 column 선택
print(arr[:2, :3])

[[0 1 2]
 [5 6 7]]


In [28]:
print(arr[:1, :1])  #> 2차원 배열!

[[0]]


In [30]:
print(arr[:2])  # arr[:2, :]

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
print(arr[:2][:3])

[[0 1 2 3 4]
 [5 6 7 8 9]]


## 3차원 배열 slicing

In [31]:
arr = np.arange(60).reshape((3, 4, 5))
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [32]:
print(arr[:2, :, :])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [33]:
print(arr[:2])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [34]:
print(arr[:1, :, :])  # 3차원 배열 slicing ==> 3차원 배열

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]]


In [35]:
print(arr[0, :, :])  # arr[0]  # 2차원 배열

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [38]:
arr = np.arange(12).reshape((3, 4))
print(arr)
print(arr[0])
print(arr[0, 0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
0


# Shape 변경


*   `np.ndarray.reshape(shape)`
*   `np.ndarray.ravel()`
*   `np.ndarray.flatten()`
*   `np.newaxis` 이용


## reshape

In [39]:
arr_1d = np.arange(12)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [41]:
# arr_1d를 (4, 3) shape의 2차원 배열로 변환
arr_2d = arr_1d.reshape((4, 3))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [42]:
# reshape의 argument를 전달할 때 자동으로 계산될 수 있는 차원에는 -1을 사용할 수 있음.
arr_2d = arr_1d.reshape((4, -1))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [43]:
arr_2d = arr_1d.reshape((-1, 4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
# 2차원 배열 -> 1차원 배열
result = arr_2d.reshape((3 * 4,))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [45]:
result = arr_2d.reshape((-1,))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
