<a href="https://colab.research.google.com/github/JakeOh/202205_itw_bd34/blob/main/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

# `np.ndarray` 속성(attribute)

In [2]:
arr = np.ones(shape=(2, 3))  # 모든 원소의 값이 1.0인 (2, 3) 모양의 배열
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [3]:
arr.dtype  # 배열의 원소들의 데이터 타입

dtype('float64')

In [4]:
arr.shape  # 모양(shape): 배열의 각 축(axis)을 따라서 있는 원소의 개수 -> tuple

(2, 3)

In [5]:
arr.ndim  # 차원(dimension): 배열의 축의 개수.

2

In [6]:
arr.size  # 크기: 배열의 원소 전체 개수

6

In [7]:
arr = np.arange(10)  # [0, 10) 범위의 정수들로 이루어진 1차원 배열.
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
arr.shape

(10,)

In [9]:
arr.ndim

1

In [11]:
arr = np.arange(1, 25).reshape((2, 3, 4))
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [12]:
arr.ndim

3

In [13]:
arr.shape

(2, 3, 4)

In [14]:
arr.dtype

dtype('int64')

# indexing

In [15]:
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [16]:
print(arr[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
print(arr[0, 0])  # arr[0][0]

[1 2 3 4]


In [18]:
print(arr[0, 0, 0])  # arr[0][0][0]

1



*   Python list의 인덱스 사용 방법: `list[i][j]...`
*   numpy ndarray의 인덱스 사용 방법:
    * `array[i][j]...`
    * `array[i, j, ...]`
