<a href="https://colab.research.google.com/github/JakeOh/202205_itw_bd34/blob/main/ml15_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ANN(Artificial Neural Network, 인공 신경망)

# Imports

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# scikit-learn
from sklearn import datasets
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_validate, train_test_split

# tensorflow, keras
import tensorflow as tf
from tensorflow import keras

In [2]:
tf.__version__  # Google Colab에 설치된 Tensorflow 버전

'2.8.2'

In [3]:
keras.__version__  # Google Colab의 Keras 버전

'2.8.0'

# Iris 데이터 셋

In [4]:
data, target = datasets.load_iris(return_X_y=True)

In [5]:
data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
target[:5]

array([0, 0, 0, 0, 0])

## petal_length, petal_width 변수만 선택한 이진 분류

In [7]:
X = data[:, 2:].copy()
y = (target != 0).astype('int')

In [8]:
X[:5]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2]])

In [13]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## SGD Classifier

In [24]:
sgd = SGDClassifier(loss='log', max_iter=10,
                    n_jobs=-1, random_state=42)

In [25]:
sgd.fit(X, y)

SGDClassifier(loss='log', max_iter=10, n_jobs=-1, random_state=42)

In [26]:
sgd.coef_

array([[9.29310825, 9.5046378 ]])

In [27]:
sgd.intercept_

array([-33.65502003])

In [28]:
pred_prob = sgd.predict_proba(X)
pred_prob[:5]

array([[9.99999993e-01, 7.23930287e-09],
       [9.99999993e-01, 7.23930287e-09],
       [9.99999997e-01, 2.85826298e-09],
       [9.99999982e-01, 1.83354387e-08],
       [9.99999993e-01, 7.23930287e-09]])

In [29]:
pred = sgd.predict(X)
pred[:5]

array([0, 0, 0, 0, 0])

In [30]:
np.mean(y == pred)

1.0

## Neural Network

In [43]:
# 신경망 모델 생성
model = keras.Sequential(layers=[keras.layers.Dense(units=1,
                                                    activation='sigmoid',
                                                    input_shape=(2,))],
                         name='iris_binary_single_layer')

In [44]:
# 신경망 모델 요약 정보: layers, parameters
model.summary()

Model: "iris_binary_single_layer"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [46]:
# 신경망 모델 컴파일: optimizer(훈련 방식), loss(손실 함수), metrics(평가 점수 함수) 설정
model.compile(optimizer='sgd', 
              loss=keras.losses.binary_crossentropy,
              metrics=keras.metrics.binary_accuracy)

In [47]:
# 신경망 훈련
model.fit(X, y, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.7656 - binary_accuracy: 0.3667
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.6364 - binary_accuracy: 0.7667
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.5557 - binary_accuracy: 0.9000
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.5067 - binary_accuracy: 0.8067
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.4744 - binary_accuracy: 0.7000
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.4534 - binary_accuracy: 0.6667
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.4378 - binary_accuracy: 0.6667
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.4271 - binary_accuracy: 0.6667
Epoch 9/10
5/5 [==============================] - 0s 5ms/step - loss: 0.4192 - binary_accuracy: 0.6667
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 0.

In [48]:
model.weights

[<tf.Variable 'dense_3/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[0.03160075],
        [0.85184544]], dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(1,) dtype=float32, numpy=array([0.01728189], dtype=float32)>]