<a href="https://colab.research.google.com/github/JakeOh/202205_itw_bd34/blob/main/ml16_cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CNN(Convolutional Neural Network, 합성곱 신경망)

# Imports

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import convolve, convolve2d, correlate, correlate2d

from sklearn import datasets
from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow import keras

# 1-D convolution

In [2]:
x = np.arange(1, 5)
x

array([1, 2, 3, 4])

In [3]:
y = np.array([1, 2])
y

array([1, 2])

In [4]:
convolve(x, y, mode='valid')

array([ 4,  7, 10])

In [6]:
convolve(x, y, mode='same')

array([ 1,  4,  7, 10])

In [7]:
convolve(x, y, mode='full')

array([ 1,  4,  7, 10,  8])

# 1-D Cross Correlation(교차 상관)

In [8]:
print(x)
print(y)

[1 2 3 4]
[1 2]


In [9]:
correlate(x, y, mode='valid')

array([ 5,  8, 11])

In [10]:
correlate(x, y, mode='same')

array([ 2,  5,  8, 11])

In [11]:
correlate(x, y, mode='full')

array([ 2,  5,  8, 11,  4])